export type {
  District,
  GeoLevel,
  Locale,
  LocalLevel,
  LocalLevelFilter,
  LocalLevelType,
  LocalLevelTypeKey,
  NamedEntity,
  NamedLabels,
  NepalLocationValue,
  Province,
  Ward,
} from "./types";
export {
  decodeWardId,
  displayName,
  encodeWardId,
} from "./types";

export {
  DISTRICTS,
  GEO_META,
  LOCAL_LEVELS,
  LOCAL_LEVEL_TYPES,
  PROVINCES,
  WARD_COUNTS,
  getDistrictById,
  getDistricts,
  getLocalLevelById,
  getLocalLevelTypeById,
  getLocalLevelTypeByKey,
  getLocalLevelTypes,
  getLocalLevels,
  getMetropolitanCities,
  getMunicipalities,
  getProvinceById,
  getProvinces,
  getRuralMunicipalities,
  getSubMetropolitanCities,
  getTypeIdForKey,
  getWardById,
  getWardCount,
  getWards,
  resolveLocalHierarchy,
  searchEntities,
  sortByName,
} from "./queries";
