import React from 'react';
import {
  Heading1,
  Type,
  Image as ImageIcon,
  Square,
  ListOrdered,
  Box,
  Rows3,
  Columns3,
  Minus,
  Space,
  Smile,
  AppWindow,
  Video,
  Star,
  Hash,
  Activity,
  Tag,
  Quote,
  AlertTriangle,
  Menu,
  PanelsTopLeft,
  Newspaper,
  Code,
  FileCode,
  Map,
  Globe,
} from 'lucide-react';
import {
  ComponentType,
  Device,
  Category,
  AdvancedStyle,
  SpacingValue,
  BorderRadiusValue,
  BoxShadow,
  DeviceVisibility,
} from './types';

export const DEVICES: Device[] = ['desktop', 'tablet', 'mobile'];

export const TRANSLATABLE_PROPS: Record<ComponentType, string[]> = {
  heading: ['text'],
  text: ['text'],
  button: ['text'],
  list: ['items'],
  image: ['alt'],
  container: [],
  flex: [],
  grid: [],
  divider: [],
  spacer: [],
  icon: [],
  icon_box: ['title', 'description'],
  video: [],
  star_rating: [],
  counter: ['label'],
  progress_bar: ['label'],
  badge: ['text'],
  quote: ['text', 'author'],
  alert: ['title', 'text'],
  nav: ['links'],
  hero: ['heading', 'subheading', 'ctaLabel'],
  'blog-card': ['title', 'excerpt', 'authorName', 'readMoreLabel', 'category'],
  html: ['code'],
  code: ['code'],
  map: ['address'],
  iframe: ['url'],
};

export const SHARED_PROPS: Record<ComponentType, string[]> = {
  heading: ['level'],
  text: [],
  button: ['href', 'target'],
  list: ['listType'],
  image: ['src'],
  container: [],
  flex: [],
  grid: [],
  divider: [],
  spacer: ['height'],
  icon: ['iconName'],
  icon_box: ['iconName'],
  video: ['url'],
  star_rating: ['rating', 'maxRating'],
  counter: ['targetNumber'],
  progress_bar: ['percentage'],
  badge: [],
  quote: [],
  alert: ['variant'],
  nav: [],
  hero: [
    'backgroundImage',
    'backgroundColor',
    'ctaUrl',
    'ctaTarget',
    'alignment',
    'overlayOpacity',
  ],
  'blog-card': ['thumbnail', 'publishDate', 'postUrl', 'imageAspectRatio'],
  html: [],
  code: ['language'],
  map: [],
  iframe: [],
};

export const COLOR_PALETTE = [
  '#ffffff',
  '#f8f9fa',
  '#e9ecef',
  '#dee2e6',
  '#ced4da',
  '#adb5bd',
  '#6c757d',
  '#495057',
  '#343a40',
  '#212529',
  '#000000',
  '#dbeafe',
  '#bfdbfe',
  '#93c5fd',
  '#60a5fa',
  '#3b82f6',
  '#2563eb',
  '#1d4ed8',
  '#1e40af',
  '#1e3a8a',
  '#fee2e2',
  '#fecaca',
  '#fca5a5',
  '#f87171',
  '#ef4444',
  '#dc2626',
  '#b91c1c',
  '#991b1b',
  '#7f1d1d',
  '#d1fae5',
  '#a7f3d0',
  '#6ee7b7',
  '#34d399',
  '#10b981',
  '#059669',
  '#047857',
  '#065f46',
  '#064e3b',
  '#fef3c7',
  '#fde68a',
  '#fcd34d',
  '#fbbf24',
  '#f59e0b',
  '#d97706',
  '#b45309',
  '#92400e',
  '#78350f',
  '#ede9fe',
  '#ddd6fe',
  '#c4b5fd',
  '#a78bfa',
  '#8b5cf6',
  '#7c3aed',
  '#6d28d9',
  '#5b21b6',
  '#4c1d95',
];

export const makeDefaultSpacing = (): SpacingValue => ({
  top: '',
  right: '',
  bottom: '',
  left: '',
  unit: 'px',
  linked: true,
});

export const makeDefaultBorderRadius = (): BorderRadiusValue => ({
  topLeft: '',
  topRight: '',
  bottomRight: '',
  bottomLeft: '',
  unit: 'px',
  linked: true,
});

export const makeDefaultBoxShadow = (): BoxShadow => ({
  enabled: false,
  x: '0',
  y: '4',
  blur: '8',
  spread: '0',
  color: '#00000040',
  inset: false,
});

export const makeDefaultDimension = (): {
  value: number | null;
  unit: 'px' | '%' | 'auto' | 'vh' | 'vw';
} => ({
  value: null,
  unit: 'auto',
});

export const DEFAULT_STYLE: AdvancedStyle = {
  align: 'left',
  paddingY: 'none',
  bg: 'none',
  width: 'full',
  height: 'auto',
  customHeight: '400',
  dimWidth: makeDefaultDimension(),
  dimHeight: makeDefaultDimension(),
  margin: makeDefaultSpacing(),
  padding: makeDefaultSpacing(),
  fontSize: '',
  fontSizeUnit: 'px',
  fontWeight: '',
  lineHeight: '',
  letterSpacing: '',
  letterSpacingUnit: 'px',
  textTransform: 'none',
  textDecoration: 'none',
  textColor: '',
  backgroundColor: '',
  backgroundImage: '',
  backgroundSize: 'cover',
  backgroundPosition: 'center center',
  backgroundRepeat: 'no-repeat',
  backgroundOverlay: null,
  borderWidth: makeDefaultSpacing(),
  borderStyle: 'none',
  borderColor: '#000000',
  borderRadius: makeDefaultBorderRadius(),
  opacity: '',
  boxShadow: makeDefaultBoxShadow(),
  customCSS: '',
  objectFit: 'cover',
  filterBlur: '',
  imageShadowPreset: 'none',
};

export const DEFAULT_VISIBILITY: DeviceVisibility = { desktop: true, tablet: true, mobile: true };

export const PADDING_MAP: Record<AdvancedStyle['paddingY'], string> = {
  none: 'py-0',
  sm: 'py-3',
  md: 'py-8',
  lg: 'py-16',
};
export const BG_MAP: Record<AdvancedStyle['bg'], string> = {
  none: 'bg-transparent',
  gray: 'bg-gray-50',
  dark: 'bg-gray-900',
};
export const ALIGN_MAP: Record<AdvancedStyle['align'], string> = {
  left: 'text-left items-start',
  center: 'text-center items-center',
  right: 'text-right items-end',
};

export const COMPONENT_LIBRARY: {
  type: ComponentType;
  label: string;
  icon: React.ElementType;
  category: Category;
  isContainer?: boolean;
  defaultProps: Record<string, string>;
  defaultStyle?: Partial<AdvancedStyle>;
}[] = [
  {
    type: 'heading',
    label: 'Heading',
    icon: Heading1,
    category: 'basic',
    defaultProps: { text: 'New heading', level: '2' },
  },
  {
    type: 'text',
    label: 'Text',
    icon: Type,
    category: 'basic',
    defaultProps: { text: 'Some descriptive text goes here.' },
  },
  {
    type: 'image',
    label: 'Image',
    icon: ImageIcon,
    category: 'basic',
    defaultProps: { src: 'https://placehold.co/800x400', alt: 'Placeholder' },
  },
  {
    type: 'button',
    label: 'Button',
    icon: Square,
    category: 'basic',
    defaultProps: { text: 'Click me' },
  },
  {
    type: 'list',
    label: 'List',
    icon: ListOrdered,
    category: 'basic',
    defaultProps: { items: 'First item\nSecond item\nThird item', listType: 'unordered' },
  },
  {
    type: 'container',
    label: 'Container',
    icon: Box,
    category: 'layout',
    isContainer: true,
    defaultProps: {},
    defaultStyle: {
      width: 'boxed',
      height: 'auto',
      customHeight: '400',
    },
  },
  {
    type: 'flex',
    label: 'Flex row',
    icon: Rows3,
    category: 'layout',
    isContainer: true,
    defaultProps: {},
    defaultStyle: {
      width: 'full',
      height: 'auto',
      customHeight: '400',
    },
  },
  {
    type: 'grid',
    label: 'Grid',
    icon: Columns3,
    category: 'layout',
    isContainer: true,
    defaultProps: {},
    defaultStyle: {
      columns: 2,
      width: 'full',
      height: 'auto',
      customHeight: '400',
    },
  },
  {
    type: 'divider',
    label: 'Divider',
    icon: Minus,
    category: 'basic',
    defaultProps: {},
  },
  {
    type: 'spacer',
    label: 'Spacer',
    icon: Space,
    category: 'basic',
    defaultProps: { height: '50' },
  },
  {
    type: 'icon',
    label: 'Icon',
    icon: Smile,
    category: 'basic',
    defaultProps: { iconName: 'Smile' },
  },
  {
    type: 'icon_box',
    label: 'Icon Box',
    icon: AppWindow,
    category: 'basic',
    defaultProps: { iconName: 'Star', title: 'Icon Box', description: 'Description goes here' },
  },
  {
    type: 'video',
    label: 'Video',
    icon: Video,
    category: 'basic',
    defaultProps: { url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' },
  },
  {
    type: 'star_rating',
    label: 'Star Rating',
    icon: Star,
    category: 'basic',
    defaultProps: { rating: '4', maxRating: '5' },
  },
  {
    type: 'counter',
    label: 'Counter',
    icon: Hash,
    category: 'basic',
    defaultProps: { targetNumber: '100', label: 'Satisfied Customers' },
  },
  {
    type: 'progress_bar',
    label: 'Progress Bar',
    icon: Activity,
    category: 'basic',
    defaultProps: { percentage: '75', label: 'Completion' },
  },
  {
    type: 'badge',
    label: 'Badge',
    icon: Tag,
    category: 'basic',
    defaultProps: { text: 'New' },
  },
  {
    type: 'quote',
    label: 'Quote',
    icon: Quote,
    category: 'basic',
    defaultProps: { text: 'This is an amazing product!', author: 'John Doe' },
  },
  {
    type: 'alert',
    label: 'Alert',
    icon: AlertTriangle,
    category: 'basic',
    defaultProps: {
      title: 'Attention',
      text: 'Please read this important message.',
      variant: 'info',
    },
  },
  {
    type: 'nav',
    label: 'Navigation Menu',
    icon: Menu,
    category: 'marketing',
    defaultProps: { links: 'Home,/\nAbout,/about\nContact,/contact' },
  },
  {
    type: 'hero',
    label: 'Hero',
    icon: PanelsTopLeft,
    category: 'marketing',
    defaultProps: {
      heading: 'Build something great',
      subheading: 'A short supporting line for your landing page.',
      backgroundImage: '',
      backgroundColor: '#0f172a',
      ctaLabel: 'Get started',
      ctaUrl: '#',
      ctaTarget: '_self',
      alignment: 'center',
      overlayOpacity: '0.45',
    },
  },
  {
    type: 'blog-card',
    label: 'Blog Card',
    icon: Newspaper,
    category: 'marketing',
    defaultProps: {
      thumbnail: 'https://placehold.co/800x450',
      title: 'Blog post title',
      excerpt: 'A short excerpt of the article goes here.',
      authorName: 'Author Name',
      publishDate: '',
      readMoreLabel: 'Read more',
      postUrl: '#',
      category: 'News',
      imageAspectRatio: '16:9',
    },
  },
  {
    type: 'html',
    label: 'HTML Embed',
    icon: Code,
    category: 'embeds',
    defaultProps: { code: '<div>Custom HTML goes here</div>' },
  },
  {
    type: 'code',
    label: 'Code Block',
    icon: FileCode,
    category: 'embeds',
    defaultProps: {
      code: 'console.log("Hello world");',
      language: 'javascript',
    },
    defaultStyle: {
      width: 'full',
    },
  },
  {
    type: 'map',
    label: 'Google Maps',
    icon: Map,
    category: 'embeds',
    defaultProps: { address: 'New York, NY' },
  },
  {
    type: 'iframe',
    label: 'Embedded Iframe',
    icon: Globe,
    category: 'embeds',
    defaultProps: { url: 'https://example.com' },
  },
];

export const CATEGORY_LABEL: Record<Category, string> = {
  basic: 'Basic',
  layout: 'Layout',
  marketing: 'Marketing',
  embeds: 'Embeds',
};

export const isContainerType = (t: ComponentType) =>
  t === 'container' || t === 'grid' || t === 'flex';
